### ISSUE TITLE
Graph Configurations

### ISSUE THREAD

**Issue by Hominnn** [Thinklab-SJTU/Bench2Drive-VL#20]
1. Can you provide Graph Configurations for all questions? It' s hard to handle such a large inference sequence. :(
2. When I user default graph configuration to open-loop inference, an OOM error occurred.
Model: Qwen2.5-VL-3B
GPU: 1*L40
Dataset: 50 scenarios in Bench2Drive-VL-base
Error：Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/inference_workers.py", line 231, in work_loop
    self.process_scenario(scenario, entry, exit)
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/inference_workers.py", line 278, in process_scenario
    res = self.ask_single_frame(scenario=scenario,
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/inference_workers.py", line 378, in ask_single_frame
    response = self.interact_with_model(question_bubble, qid, frame_number)
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/inference_workers.py", line 321, in interact_with_model
    response = self.ask_model(question_bubble, curr_context)
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/inference_workers.py", line 443, in ask_model
    response = self.model.interact(question_bubble, curr_context)
  File "/B2D/Bench2Drive-VL-main/B2DVL_Adapter/models/qwen25.py", line 189, in interact
    generated_ids = self.model.generate(**inputs, max_new_tokens=1024)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2326, in generate
    result = self._sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 3286, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 1793, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 557, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens_now, position_embeddings=position_embeddings)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 350, in forward
    hidden_states = hidden_states + self.attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 319, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.22 GiB. GPU 0 has a total capacity of 44.32 GiB of which 18.30 GiB is free. Process 952598 has 26.01 GiB memory in use. Of the allocated memory 25.12 GiB is allocated by PyTorch, and 400.02 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by MeteorCollector** [comment]
Hello, 1. What does Graph Configurations for all questions mean? You can find qids of all questions [here](https://thinklab-sjtu.github.io/Bench2Drive-VL/docs/references/supported-vqas) and graph grammar [here](https://thinklab-sjtu.github.io/Bench2Drive-VL/docs/references/graph-config). 
2. What is the config file you used? When does this OOM happen? Maybe I can help you out if more information is provided. You can contact me via my email shao-yq@sjtu.edu.cn if you have more questions about debugging.

**Comment by Hominnn** [comment]
> Hello, 1. What does Graph Configurations for all questions mean? You can find qids of all questions [here](https://thinklab-sjtu.github.io/Bench2Drive-VL/docs/references/supported-vqas) and graph grammar [here](https://thinklab-sjtu.github.io/Bench2Drive-VL/docs/references/graph-config). 2. What is the config file you used? When does this OOM happen? Maybe I can help you out if more information is provided. You can contact me via my email [shao-yq@sjtu.edu.cn](mailto:shao-yq@sjtu.edu.cn) if you have more questions about debugging.

1. I found that the default configuration only covers a small number of questions. For some questions, I don’t know the logical relationship between them, so I can’t set the graph configuration.
2. The second problem occurred when I was doing an open-loop inference.
This is CMD：
`python inference.py --model Qwen2.5VL \
                    --model_path ../../model/Qwen2.5-VL-3B-Instruct \
                    --config_dir ./infer_configs/open_loop_inference_cfg.json \
                    --image_dir ../../dataset/Bench2Drive-mini \
                    --vqa_dir ../../dataset/B2D-mini-vqa \
                    --num_workers 1 \
                    --out_dir ./infer_outputs/qwen2.5vl3b_zero_shot`
This is open_loop_inference_cfg.json：
`{
    "TASK_CONFIGS": {
        "INFER_SUBSET": false, 
        "USE_CHECKPOINT": true, 
        "SUBSET_FILE": "", 
        "CHECKPOINT_FILE": "",
        "ENTRY_EXIT_FILE": "", 
        "FRAME_PER_SEC": 10 
    },
    "INFERENCE_BASICS": {
        "INPUT_WINDOW": 1,
        "CONVERSATION_WINDOW": 2,
        "USE_ALL_CAMERAS": true,
        "NO_HISTORY_MODE": false,
        "APPEND_QUESTION": true,
        "APPENDIX_FILE": "" 
    }
}`
After debugging, I found stitching six images into two images and inputting them into Qwen2.5-VL-3B, a OOM error occurred. I believe Qwen can handle such high-resolution images, but I don't know why the OOM error occurs.
This is the Q/K/V' shape, I think this might be the problem：
`Q shape: torch.Size([16, 43776, 80]), K shape: torch.Size([16, 43776, 80]), V shape: torch.Size([16, 43776, 80])`

**Comment by MeteorCollector** [comment]
1. We don't provide logical relationship for all questions because making the VLM answer all questions during inference is impractical (it takes forever!), and we didn't evaluate them all in our baseline as well. It is left free for users to configure...
2. 43776 not seems good... I will check it on my machine, plz stay tuned.

**Comment by Hominnn** [comment]
1. I find **general_chain.md** in **B2DVL_Adapter**. Although the questions it provides are not complete, I used ChatGPT to generate a usable Graph configuration based on my goals.
2. I found that flash attention was not used during inference, but sdpa was used. So I changed the default configuration in your code file **qwen25.py**.
`        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_path, low_cpu_mem_usage=True,torch_dtype=torch.bfloat16,attn_implementation="flash_attention_2"
        )`
It works! :)

**Comment by Hominnn** [comment]
I find another question when using Python thread for multi-gpu inference. After debugging, I found that there may be a problem with concurrent model loading. I solved this problem by loading the model serially before work_loop. Now multi-gpu inference can be performed. (Python's thread is not easy to use)
